version: 2.1

jobs:
  lsif-go:
    docker:
      - image: sourcegraph/lsif-go@sha256:14ecaa6c0dff7988783ac5d8bd7d02be9bc648addc2074a47657a33597492583
    steps:
      - checkout
      - run: lsif-go
      - run: src lsif upload -no-progress
  install-deps:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --no-progress
      - save_cache:
          paths:
            - node_modules
          key: dependencies
  lsif-node:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: mv /home/circleci/project/node_modules .
      - run: lsif-tsc -p .
      - run: src lsif upload -no-progress

workflows:
  lsif-go:
    jobs:
      - lsif-go
  lsif-node:
    jobs:
      - install-deps
      - lsif-node:
          requires:
            - install-deps
